#!/bin/bash
# vim: set ft=sh

set -exuo pipefail

base=$PWD

VERSION=$(cat "$base"/gr-version/number)
if [ -z "${VERSION:-}" ]; then
  echo "missing version number"
  exit 1
fi

cd gr-release-develop

tarball_name="garden-runc-${VERSION}.tgz"
tarball_path="$base/bosh-release/$tarball_name"
tarball_dir="$(dirname "$tarball_path")"

mkdir -p $tarball_dir
echo "this is a ghost release, do not use for actual boshness" > ghost_bosh_release
tar czf $tarball_name ghost_bosh_release

mv $tarball_name $tarball_dir
