#!/bin/bash
# vim: set ft=sh

set -exuo pipefail

base=$PWD

GARDEN_VERSION=$(cat "$base"/gr-version/number)
if [ -z "${GARDEN_VERSION:-}" ]; then
  echo "missing garden version number"
  exit 1
fi

CANDIDATE_DIR=$base/gr-candidate-tarball

(
cd gr-release-develop
git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

RELEASE_YML=$PWD/releases/garden-runc/garden-runc-${GARDEN_VERSION}.yml
tarball_name="garden-runc-${GARDEN_VERSION}.tgz"
tarball_path="$base/final-release/${tarball_name}"

echo "this is a ghost release, do not use for actual boshness" > "${tarball_name%.*}"

if [ -e "$RELEASE_YML" ]; then
  echo "release already created; making tarball..."
  tar czf "$tarball_name" "${tarball_name%.*}"
  mv "$tarball_name" "$(dirname "$tarball_path")"
else
  echo "finalizing release"
  mv "${CANDIDATE_DIR}"/garden-runc-*.tgz "$(dirname "$tarball_path")"
  git add -A
  git commit -m "release v${GARDEN_VERSION}"
fi

cp -r . ../release/master
)

# prepare github release
echo "boo" > "github-release/gdn-${GARDEN_VERSION}"
