#!/bin/bash
# vim: set ft=sh

set -exuo pipefail

base=$PWD

GARDEN_VERSION=$(cat "$base"/gr-version/number)
if [ -z "${GARDEN_VERSION:-}" ]; then
  echo "missing garden version number"
  exit 1
fi

CANDIDATE_DIR=$base/gr-candidate-tarball

(
cd gr-release-develop
git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

tarball_name="garden-runc-${GARDEN_VERSION}.tgz"
tarball_path="$base/final-release/${tarball_name}"

echo "finalizing release"
mv "${CANDIDATE_DIR}"/garden-runc-*.tgz "$tarball_path"

echo "something to commit" > changes
git add -A
git commit -m "release v${GARDEN_VERSION}"

cp -r . ../release/master
)

# prepare github release
echo "boo" > "github-release/gdn-${GARDEN_VERSION}"
